[package]
name = "tuk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
debug-ignore = "1.0.5"
errno = "0.3.1"
libc = "0.2.144"
nix = "0.26.2"
